apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: mydocker.murad.com:5000/nginx:latest
    ports:
      - containerPort: 80
